### PR TITLE
Navigation Fixes

### LINKED ISSUE #422: Fix navigation throughout the app

### PR DESCRIPTION
**Pull request by manunam2002**
### Description

This PR fixes all navigation incoherencies across the app. Notably it handles complex/long navigations by clearing and setting the navigation back stack. It also reorganises and tidies `Route`,`Screen`, `TopLevelDestination`, as well as reorganising NavHosts for the different UIs in `MainActivity`.

### Changes Made

- **Reorganize navigation in `MainActivity` & `NavigationActions`**: 
  - Made sure that a `Route` is defined for each entry in the `NavHost`s and a `Screen` is defined for each entry of a nested `navigation`.
  - Renamed and rearranged `Route`s and `Screen`s to make sure each name is clear and consistent.
- **Addition & Changes in `NavigationActions` functions**: 
  - Changed `navigateTo(toplevelDestination)` function to effectively clear the back stack up to `startDestination`.
  - Removed potentially dangerous `goBackTo(screen)` function.
  - Created `navigateAndSetBackStack(screen, backStackRoutes)` that clears the back stack up to `startDestination`, adds `backStackRoutes` to the stack and the navigates to `screen`.
- **Navigation correction across the UI**: used the newly created `navigateAndSetBackStack(screen, backStackRoutes)` function for navigations that require the back stack to be cleared and resetted, notably for the following navigations:
  - `CreateRequestScreen` -> `BookingScreen`
  - `EditRequestScreen` -> `RequestOverview`
  - `ProviderInfoScreen` -> `BookingScreen`
  - `BookingScreen` -> `ChatScreen`
  - `CreateReviewScreen` -> `RequestsOverview`
  - all `BottomBar` navigation now uses `navigateTo(toplevelDestination)` instead of `navigateTo(screen)` 
- **Tests adaptation**: Adapted UI and unit tests to match the navigation changes.

### Related Issues

Fixes #422 

**Note**: Map Redesign PR #446 was merged into this one

### CODE REVIEW

**Review by yshdb5 — APPROVED** [review]
### Overall Comment  
This PR makes critical improvements to the app's navigation, ensuring a more logical structure and robust handling of complex navigation flows. It significantly enhances maintainability and user experience.  

### Strong Elements  
- **Improved Readability**: Grouping routes and screens under coherent categories (e.g., Authentication, Seeker UI, Provider UI) simplifies the code and improves comprehension.  
- **Enhanced Navigation Logic**: The `navigateAndSetBackStack` function adds precise control over navigation flows, effectively addressing issues with back stack management and improving overall navigation performance.  
- **Consistency and Clarity**: Renaming routes and screens with more descriptive names (e.g., `Route.SEEKER_OVERVIEW` instead of `Route.SERVICES`) increases code clarity and makes intent more explicit.  

### Conclusion  
This PR is a huge step forward in improving navigation structure and logic, providing a cleaner, more maintainable codebase and a better user experience. These additions work perfectly, it's a pleasure to use. Excellent work!

File: app/src/main/java/com/android/solvit/MainActivity.kt
Comment (achillet3) [inline app/src/main/java/com/android/solvit/MainActivity.kt:1]: ✅ Excellent organization of navigation flow with clear authentication-based routing ❗ Consider removing the !! operator on line 162 and using an else if (user.role == "seeker") inside the first user?.let block.

```
// Before (current code):
val startDestination =
    if (user == null) Route.AUTH
    else if (user!!.role == "seeker") Route.SEEKER_REGISTRATION else Route.PROVIDER_REGISTRATION

NavHost(navController = navController, startDestination = startDestination) {
    // Authentication
    navigation(startDestination = Screen.OPENING, route = Route.AUTH) {
        composable(Screen.OPENING) { OpeningScreen(navigationActions) }
        // ...
    }
}

// After (improved version):
val startDestination = when {
    user == null -> Route.AUTH
    user.role == "seeker" -> Route.SEEKER_REGISTRATION
    user.role == "provider" -> Route.PROVIDER_REGISTRATION
    else -> {
        Log.w("MainActivity", "Unknown user role: ${user.role}, defaulting to AUTH")
        Route.AUTH
    }
}

// Wrap the NavHost in a user state handler
user?.let { nonNullUser ->
    NavHost(navController = navController, startDestination = startDestination) {
        // Authentication
        navigation(startDestination = Screen.OPENING, route = Route.AUTH) {
            composable(Screen.OPENING) { OpeningScreen(navigationActions) }
            // ...
        }
        
        // Registration flows
        composable(Route.SEEKER_REGISTRATION) {
            SeekerRegistrationScreen(
                seekerProfileViewModel,
                navigationActions,
                locationViewModel,
                authViewModel
            )
        }
        
        composable(Route.PROVIDER_REGISTRATION) {
            ProviderRegistrationScreen(
                listProviderViewModel,
                navigationActions,
                locationViewModel,
                providerViewModel,
                packageProposalViewModel,
                packagesAssistantViewModel
            )
        }
    }
} ?: run {
    // Handle case where user is null - show auth flow
    NavHost(navController = navController, startDestination = Route.AUTH) {
        navigation(startDestination = Screen.OPENING, route = Route.AUTH) {
            composable(Screen.OPENING) { OpeningScreen(navigationActions) }
            // ... other auth screens
        }
    }
}
```

File: app/src/main/java/com/android/solvit/seeker/ui/request/RequestComposables.kt
Comment (achillet3) [inline app/src/main/java/com/android/solvit/seeker/ui/request/RequestComposables.kt:1]: ❗ The empty back stack (listOf()) could lead to a dead end in navigation ✅ Good error handling with try-catch block 🔧 Suggestion: Consider adding at least one fallback route in the back stack:

```
navigationActions.navigateAndSetBackStack(Route.REQUESTS_OVERVIEW, listOf(Route.SEEKER_OVERVIEW))
```

File: app/src/main/java/com/android/solvit/MainActivity.kt [hunk 1]
```diff
@@ -203,66 +207,29 @@ fun SeekerUI(
...
+  NavHost(navController = navController, startDestination = Route.SEEKER_OVERVIEW) {
+    // Overview
+    composable(Route.SEEKER_OVERVIEW) { ServicesScreen(navigationActions, listProviderViewModel) }
+
+    // Providers
+    composable(Route.PROVIDERS_LIST) {
+      SelectProviderScreen(
+          seekerProfileViewModel,
+          listProviderViewModel,
+          user!!.uid,
```
Comment (achillet3) [inline app/src/main/java/com/android/solvit/MainActivity.kt:219]: ❗ Unsafe use of !! operator with user.uid 🔧 Suggestion: Add proper null safety:

```suggestion
composable(Route.PROVIDERS_LIST) {
    user?.let { nonNullUser ->
        SelectProviderScreen(
            seekerProfileViewModel,
            listProviderViewModel,
            nonNullUser.uid,
            navigationActions,
            locationViewModel)
    } ?: run {
        // Handle null user case, perhaps navigate to login
        navigationActions.navigateTo(Route.AUTH)
    }
}
```

File: app/src/main/java/com/android/solvit/shared/ui/navigation/NavigationActions.kt
Comment (achillet3) [inline app/src/main/java/com/android/solvit/shared/ui/navigation/NavigationActions.kt:1]: Route strings should use lowercase with underscores for consistency and to avoid potential issues with spaces in navigation.

File: app/src/main/java/com/android/solvit/shared/ui/chat/ChatScreen.kt [hunk 2]
```diff
@@ -474,7 +474,7 @@ fun AiSolverHeader(navigationActions: NavigationActions) {
         }
       },
       navigationIcon = {
-        IconButton(onClick = { navigationActions.navigateTo(Route.SERVICES) }) {
+        IconButton(onClick = { navigationActions.goBack() }) {
```
Comment (achillet3) [inline app/src/main/java/com/android/solvit/shared/ui/chat/ChatScreen.kt:477]: ✅ Good use of simple back navigation for chat ❗ However, there's no handling of empty back stack cases 🔧 Suggestion: Add a fallback destination:

```suggestion
IconButton(
    onClick = { 
        if (!navigationActions.canGoBack()) {
            navigationActions.navigateTo(Route.INBOX)
        } else {
            navigationActions.goBack()
        }
    }
) {
    Icon(Icons.Default.ArrowBack, contentDescription = "Back")
}
```

**Review by achillet3 — APPROVED** [review]
#### Strengths 🌟
1. Navigation Architecture
- Well-organized navigation structure in MainActivity.kt with clear separation between authentication, seeker, and provider flows
- Excellent addition of navigateAndSetBackStack function for handling complex navigation scenarios
- Removal of the potentially dangerous goBackTo function
2. Code Organization
- Clear grouping of routes in NavigationActions.kt by feature area (Auth, Seeker UI, Provider UI, Shared UI)
- Consistent separation between Route and Screen objects

#### Overall Assessment ⭐
- The PR significantly improves the navigation architecture and makes it more maintainable. 

#### Potential Improvements

- Update route string format to use lowercase with underscores
- Address null safety in MainActivity.kt
- Review and add appropriate fallback routes for back stack management

File: app/src/main/java/com/android/solvit/seeker/ui/request/RequestComposables.kt
Comment (manunam2002) [reply app/src/main/java/com/android/solvit/seeker/ui/request/RequestComposables.kt:1]: I just don't remove the graph `startDestination` wich means we can safely pass an empty list if we just want the startDestination on the stack

File: app/src/main/java/com/android/solvit/MainActivity.kt
Comment (manunam2002) [reply app/src/main/java/com/android/solvit/MainActivity.kt:1]: The non-null assert is fine as we check if the user is null just before, also the NavHost in the shared UI should be totally accessible if the user is null (first sign up or just after logout)

File: app/src/main/java/com/android/solvit/MainActivity.kt (hunk 1 above)
Comment (manunam2002) [reply app/src/main/java/com/android/solvit/MainActivity.kt:219]: If we enter this screen the user is necessarily non-null, the check is done in `SolvItApp`

File: app/src/main/java/com/android/solvit/shared/ui/navigation/NavigationActions.kt
Comment (manunam2002) [reply app/src/main/java/com/android/solvit/shared/ui/navigation/NavigationActions.kt:1]: Okay will do that
