### PR TITLE
Refactor Bottom Navigation Bar for Dual Role (Seeker & Provider) with Bug Fixes

### LINKED ISSUE #244: Modify the BottomNavigation menus UI
•⁠  ⁠Make the BottomNavigation menu less transparent for both the Providers and Seekers menus. Their designs should match that of the Figma.
•⁠  ⁠⁠For the Providers' BottomNavigation menu, get rid of the curved part which is useless since there is no button above.

The Seekers' BottomNavigation menu should look like this:

Image

And the Providers' one should simply not have the curve nor the "+" button.

### PR DESCRIPTION
**Pull request by aoutz**
### Description:
This PR refactors the bottom navigation bar to support both seeker and provider roles. Key updates:
- **Unified Navigation Bar**: Now adaptable for both roles, reducing code duplication.
- Role-Based FAB: The FloatingActionButton (FAB) icon and action adjust based on user role:
       - **Seeker**: FAB links to request creation.
       - **Provider**: FAB links to job requests.
- **Bug Fixes**: Resolved issues with tab selection and navigation highlighting.

###  Testing:
- Verified correct FAB icon and action for each role.
- Ensured tab highlighting accurately reflects the active screen.

### Related Issues: 
- Fixes #244 

This refactor improves maintainability and fixes navigation bugs.

### CODE REVIEW

File: app/src/main/java/com/android/solvit/seeker/ui/navigation/BottomNavigationMenu.kt [hunk 1]
```diff
@@ -90,30 +91,43 @@ fun SeekerBottomNavigationMenu(
...
+                    .offset(x = width * 0.5f - 53.dp)
+                    .align(Alignment.TopCenter)
+                    .testTag(TopLevelDestinations.CREATE_REQUEST.toString()),
+            shape = CircleShape,
+            containerColor = Color(0xFF0099FF)) {
+              Icon(
+                  if (tabList == LIST_TOP_LEVEL_DESTINATION_CUSTOMER) Icons.Outlined.Add
+                  else Icons.Outlined.CheckCircle,
+                  contentDescription =
+                      if (tabList == LIST_TOP_LEVEL_DESTINATION_CUSTOMER) "Add" else "Myjobs",
```
Comment (achillet3) [inline app/src/main/java/com/android/solvit/seeker/ui/navigation/BottomNavigationMenu.kt:127]: Nit: The content description does not seem to be consistent with the textId for both Screen and the My Jobs top level destination. It could be changed to "My Jobs"

**Review by achillet3 — COMMENTED** [review]
# Overall Comments
- Excellent implementation of this dual role navigation bar. It looks very good and behaves correctly
- The Navigation Bar is now common to both Seeker and Provider and should thus be placed in the shared folder instead of the Seeker's

# Potential Improvements
- The navigation when clicking on the new role-based FAB is not tested

**Review by manunam2002 — APPROVED** [review]
### Feedback
- **Code Refactoring**: The unification of the navigation bar for both seeker and provider roles is a significant improvement, as it reduces code duplication and enhances maintainability. The introduction of the `BottomNavigationMenu` component and role based `FloatingActionButton` ensures consistency across different roles.

- **Bug Fixes**: Resolving the issues with tab selection and navigation highlighting improves the overall user experience by ensuring the correct visual feedback is provided when navigating between tabs.

- **Testing**: Comprehensive testing was conducted to verify the correct behavior of the FAB icon and action for each role.

**Review by achillet3 — APPROVED** [review]
LGTM!

**Review by yshdb5 — APPROVED** [review]
### Overall Comment
This pull request effectively refactors the bottom navigation bar to support both seeker and provider roles, which improves the maintainability and functionality of the application. The changes also include bug fixes related to tab selection and navigation highlighting, ensuring a smoother user experience.

### Strong Elements
- **Unified Navigation Bar**: The refactoring to a unified navigation bar for both roles is a smart move. It reduces code duplication and makes the navigation logic more maintainable.
- **Role-Based FAB**: Implementing a role-based FloatingActionButton (FAB) that changes its icon and action based on the user role is a clever and user-friendly feature.
- **Bug Fixes**: Addressing bugs in tab selection and navigation highlighting enhances the usability and reliability of the app.

### Conclusion
Overall, this pull request is well-executed and brings significant improvements to the navigation system of the application. The refactor not only enhances maintainability but also resolves existing bugs, contributing to a better user experience. A bit more attention to documentation and testing could make these changes even more robust. Great job!
